# Generated by Django 4.1.2 on 2022-10-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('coupe', models.BooleanField(default=False)),
                ('topSpeed', models.IntegerField(default=0)),
                ('dateOfPurchase', models.DateField()),
            ],
        ),
    ]
