# Generated by Django 4.1.2 on 2022-11-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='carName',
        ),
    ]
